openapi: 3.0.3
info:
  title: Alta E-Commerce API
  version: 1.0.1
  description: File ini digunakan untuk Menampilkan OPEN API Aplikasi Ecommerce
 
tags:
  - name: Auth
    description: API Endpoint Authentication
  - name: Users
    description: API Endpoint Users
  - name: Products
    description: API Endpoint Products
  - name: Carts
    description: API Endpoint Carts
  - name: Orders
    description: API Endpoint Orders
servers:
  - url: http://localhost:8000/api/{version}
    description: URL untuk fase development
    variables:
      version:
        default: v1
        enum:
          - "v1"
          - "v2"
#-------------------------------
# Authentication (login)
#-------------------------------
paths: 
  /login:
    post:
      tags:
        - "Authentication"
      summary: user login with credentials
      description: Untuk login Ke dalam Sistem dengan credentials yang dimiliki
      requestBody:
        $ref: '#/components/requestBodies/LoginBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message: 
                    type: string
                    example: "Success Login"
                  data:
                    type: object
                    $ref: "#/components/schemas/SimpleUserSchema"
                  token:
                    type: string
        400:
          $ref: "#/components/responses/400BadRequest"
        401:
          $ref: "#/components/responses/401UnauthorizedError"
#-------------------------------
# Users Section
#-------------------------------
# User Register  
  /register:
    post:
      tags:
        - "Users"
      summary: Register new user
      description: Create new user
      requestBody:
        $ref: '#/components/requestBodies/UsersBody' 
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 201
                  message: 
                    type: string
                    example: "Success register user"
                  data:
                    type: object
                    $ref: "#/components/schemas/UserResponse"
                  status:
                    type: boolean
                    example: true
        400:
          $ref: "#/components/responses/400BadRequest"
        500:
          $ref: "#/components/responses/500InternalServerError"

# GetById User
  /users/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          minimum: 1
        description: the user ID
    get:
      tags:
        - "Users"
      description: Mengambil data user berdasarkan ID yang ada
      summary: Get a user by ID
      responses:
        200:
          description: OK
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: users exist
                  data:
                    type: object 
                    $ref: "#/components/schemas/SimpleUserSchema"
        404:
          $ref: "#/components/responses/404NotFound"        
# Update User    
    put:
      tags:
        - "Users"
      security:
        - bearerAuth: []
      description: Mengubah Data User berdasarkan id yang ada
      summary: Ubah data user berdasarkan id
      requestBody:
          $ref : "#/components/requestBodies/UsersBody"
      responses:
        200:
          description: OK
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: data berhasil diupdate
                  data:
                    type: object  
                    $ref: "#/components/schemas/UserSchema" 
        401:
          $ref: "#/components/responses/401UnauthorizedError"
        404: 
          $ref: "#/components/responses/404NotFound"              
  # Delete user
    delete:
      tags:
        - "Users"
      security:
        - bearerAuth: []
      description: Menghapus Data User yang sudah tidak digunakan
      summary: Hapus data user berdasarkan user id
      responses:
        200:
          description: "Success Request"
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                    example: data berhasil dihapus
                  data:
                    type: object 

#-------------------------------
# Products Section
#-------------------------------
# Get all products
  /products:
    parameters:
        - $ref: "#/components/parameters/pagesParam"
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
    get:
      tags:
        - "Products"  
      description: Get all data Product 
      summary: Get all products  
      responses:
        200:
          $ref: "#/components/responses/200OkPaginate"
        400:
          $ref: "#/components/responses/400BadRequest"
        404:
          $ref: "#/components/responses/404NotFound"
        500:        
          $ref: "#/components/responses/500InternalServerError"  
    
    #Create new products
    post:
      tags:
        - "Products"
      security:
        - bearerAuth: []
      summary: Tambah product Baru
      description: Tambah User untuk disimpan ke database
      requestBody:
        $ref: '#/components/requestBodies/ProductsBody'
        
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 201
                  message: 
                    type: string
                    example: "Success add product"
                  data:
                    type: object
                    $ref: "#/components/schemas/SimpleProductSchema"
        401:
          $ref: "#/components/responses/401UnauthorizedError"
        400:
          $ref: "#/components/responses/400BadRequest"
        500:
          $ref: "#/components/responses/500InternalServerError"
  
  /categories/{categoryId}/products:
    parameters:
      - in: path
        name: categoryId
        required: true
        schema:
          type: integer
          minimum: 1
        description: the category ID
    get:
      tags:
        - "Products"  
      description: Get all data Product berdasarkan produk kategori 
      summary: Get all products by product_category_id
      responses:
        200:
          $ref: "#/components/responses/200OkPaginate"
        400:
          $ref: "#/components/responses/400BadRequest"
        404:
          $ref: "#/components/responses/404NotFound"
        500:        
          $ref: "#/components/responses/500InternalServerError" 

  #GetById Products
  /products/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          minimum: 1
        description: the user ID
    get:
      tags:
        - "Products"
      description: Mengambil data user yang berdasarkan id yang ada
      summary: Ambil data Product berdasarkan product ID
      responses:
        200:
          description: OK
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: data exist
                  data:
                    type: object
                    $ref: "#/components/schemas/SimpleProductSchema"
        404:
          $ref: "#/components/responses/404NotFound"
    put:
      tags:
        - "Products"
      security:
        - bearerAuth: []
      description: Mengubah Data Product berdasarkan product ID yang ada
      summary: Ubah data Product berdasarkan product ID
      requestBody:
        $ref: "#/components/requestBodies/ProductsBody"
      responses:
        200:
          description: OK
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: data berhasil diupdate
                  data:
                    type: object  
                    $ref: "#/components/schemas/ProductSchema" 
        400:
          $ref: "#/components/responses/400BadRequest"
        401:
          $ref: "#/components/responses/401UnauthorizedError"
        500:
          $ref: "#/components/responses/500InternalServerError"                  
    delete:
      tags:
        - "Products"
      security:
        - bearerAuth: []
      description: Menghapus Data product sesuai product ID
      summary: Hapus data product berdasarkan product ID
      responses:
        200:
          description: OK
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: data berhasil dihapus
                  data:
                    type: object
        400:
          $ref: "#/components/responses/400BadRequest"
        401:
          $ref: "#/components/responses/401UnauthorizedError"

  /carts:
    get:
      tags:
        - "Carts"
      description: Get all Cart Yang Sudah ada
      summary: Get All User Cart
      parameters:
        - name: User
          description: User Id
          in: query
          schema:
            type: integer
        - name: Product
          description: product id
          in: query
          schema:
            type: string
        - name: Total
          description: Total Harga
          in: query
          schema:
            type: string
        - name: Qty
          description: Berapa Qty
          in: query
          schema:
            type: string
        - name: Status
          description: Status Cart
          in: query
          schema:
            type: string
      responses:
        200:
          description: "Success Request"
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object 
                    $ref: "#/components/schemas/CartSchema"
                
          $ref: "#/components/responses/500InternalServerError"  
    post:
      tags:
        - "Carts"
      summary: Tambah Product Ke Carts
      description: Tambah Produk Untuk Dimasukkan ke Carts
      parameters:
        - name: User
          description: User Id
          in: query
          schema:
            type: integer
        - name: Product
          description: product id
          in: query
          schema:
            type: string
        - name: Total
          description: Total Harga
          in: query
          schema:
            type: string
        - name: Qty
          description: Berapa Qty
          in: query
          schema:
            type: string
        - name: Status
          description: Status Cart
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            #  $ref : "#/components/schemas/User"
            example:
              user_id: "1"
              product_id: "2"
              total: "20000"
              qty: "10"
              status: "ready"
      responses:
        201:
          description: "Success add user"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 1
                  message: 
                    type: string
                    example: "Success add cart"
                  data:
                    type: object
                 #   $ref: "#/components/schemas/User"
              example:
                code: 201
                message: success insert cart
                
        500:
          $ref: "#/components/responses/500InternalServerError"
  
  /carts/{id}:
    put:
      tags:
        - "Carts"
      description: Mengubah Data Cart Berdasarkan User id
      summary: Ubah data cart berdasarkan user id
      parameters:
        - name: User
          description: user_id
          in: query
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
            #  $ref : "#/components/schemas/User"
            example:
              user_id: "1"
              product_id: "2"
              total: "70000"
              qty: "10"
              status: "ready" 

      responses:
        200:
          description: "Success Request"
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                    example: data berhasil diupdate
                  data:
                    type: object  
                 #   $ref: "#/components/schemas/User" 
                example:
                  message: data berhasil diupdate
                  
                               
    delete:
      tags:
        - "Carts"
      description: Menghapus Data Cart Yang Tidak Terpakai
      summary: Hapus data cart berdasarkan user id
      parameters:
        - name: User
          description: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "Success Request"
          content:
            "application/json":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                    example: data berhasil dihapus
                  data:
                    type: object       
  #-------------------------------
  # orders Section
  #-------------------------------
  /orders:
    post:
      tags:
        - "Orders"
      description: Create new transaction orders
      summary: make transaction orders
      requestBody:
        $ref: '#/components/requestBodies/OrderBody'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 201
                  message: 
                    type: string
                    example: "Success register user"
                  data:
                    type: object
                    $ref: "#/components/schemas/UserResponse"
                  status:
                    type: boolean
                    example: true
        400:
          $ref: "#/components/responses/400BadRequest"
        500:
          $ref: "#/components/responses/500InternalServerError"
  
         
components:
  #-------------------------------
  # Reusable security schemes
  #-------------------------------
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  #-------------------------------
  # Reusable schemas (data models)
  #-------------------------------
  schemas:
    LoginSchema:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: gadipuranto@gmail.com
        password:
          type: string
          example: admin1234

    SimpleUserSchema:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Galang Adi Puranto
        email:
          type: string
          example: gadipuranto@gmail.com
        hp:
          type: string
          example: "08986817477"

    CartSchema:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        product_id:
          type: integer
          example: 2
        total_price:
          type: number
          format: double
          example: 16000000
        total_qty:
          type: integer
          example: 25
        status:
          type: string
          example: "ready"
    
    OrderSchema:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        product_id:
          type: integer
          example: 2
        total_price:
          type: number
          format: double
          example: 16000000
        total_qty:
          type: integer
          example: 25
        status:
          type: string
          example: "ready"

    OrderInCartRequest:
      type: object
      properties:
        user_id: 
          type: integer
          example: 1
        cart_id:
          type: integer
          example: 2
        total_price:
          type: number
          example: 760000
        total_qty:
          type: number
          example: 4

    OrderProductsRequest:
      type: object
      properties:
        user_id: 
          type: integer
          example: 1
        total_price:
          type: number
          example: 760000
        total_qty:
          type: number
          example: 4
    
    AddressSchema:  
      type: object
      properties:
        id: 
          type: integer
          example: 1
        user_id: 
          type: integer
          example: 1
        address:
          type: string
          example: Jl. Sultan Agung 1
        kodepos:
          type: number
          example: 54321
    
    SimpleAddressSchema:  
      type: object
      properties:
        address:
          type: string
          example: Jl. Sultan Agung 1
        kodepos:
          type: number
          example: 54321    

    ListProductSchema:
      type: array
      items:
        $ref: '#/components/schemas/SimpleProductSchema'

    SimpleProductSchema:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Matchbook M1 Pro
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi luctus congue viverra. Nulla tempus a nibh egestas dapibus. Donec feugiat arcu ut metus faucibus, eget fringilla erat mattis. 
        price:
          type: number
          format: double
          example: 16000000
        stok:
          type: integer
          example: 25
        images:
          type: string
          format: binary
          example: http://localhost:8001/images/demo.png
        user_id:
          type: integer
          example: 1

    ProductSchema:
      type: object
      required:
        - name
        - price
        - stok
        - user_id
        - product_category_id
      properties:
        name:
          type: string
          example: Matchbook M1 Pro
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi luctus congue viverra. Nulla tempus a nibh egestas dapibus. Donec feugiat arcu ut metus faucibus, eget fringilla erat mattis. 
        price:
          type: number
          format: double
          example: 16000000
        stok:
          type: integer
          example: 25
        images:
          type: string
          format: binary
        product_category_id:
          type: integer
          example: 2
        user_id:
          type: integer
          example: 1

    UserSchema:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: Galang Adi Puranto
        dob:
          type: string
          example: "1999-10-13"
        gender:
          type: string
          example: L
        email:
          type: string
          example: gadipuranto@gmail.com
        phone:
          type: string
          example: "08986817477"
        password:
          type: string
          example: admin1234

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Galang Adi Puranto
        email:
          type: string
          example: gadipuranto@gmail.com
        phone:
          type: string
          example: "08986817477"
        
#-------------------------------
# Reusable operation parameters
#-------------------------------
  parameters:
    pagesParam:      # Can be referenced via '#/components/parameters/pagesParam'
      name: page
      in: query
      description: Number of start pages.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1

    offsetParam:      # Can be referenced via '#/components/parameters/offsetParam'
      name: offset
      in: query
      description: Number of items to skip before returning the results.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0

    limitParam:       # Can be referenced as '#/components/parameters/limitParam'
      name: limit
      in: query
      description: Maximum number of items to return.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 10

#-------------------------------
# Reusable request bodies
#-------------------------------
  requestBodies:
    OrderBody:
      description: A JSON object containing orders information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderInCartRequest'
    LoginBody:
      description: A JSON object containing login information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginSchema'
    UsersBody:
      description: A JSON object containing users information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserSchema'
    ProductsBody:
      description: A JSON object containing products information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductSchema'
#-------------------------------
# Reusable responses
#-------------------------------
  responses:
    200OkPaginate:
      description: Ok
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 200
              message: 
                type: string
                example: Ok
              total:
                type: integer #total items 50
                example: 40
              per_page:
                type: integer #limit 15
                example: 10
              current_page:
                type: integer #1
                example: 1
              last_page:
                type: integer #4
                example: 4
              first_page_url:
                type: string #http://localhost:8000?page=1
                example: http://localhost:8000?page=1
              last_page_url:
                type: string
                example: http://localhost:8000?page=4
              next_page_url:
                type: string
                example: http://localhost:8000?page=2
              prev_page_url:
                type: string
                default: 
              from:
                type: integer #offset
                example: 1
              to:
                type: integer #limit
                example: 10
              data:
                type: object
                $ref: "#/components/schemas/ListProductSchema"
           
    400BadRequest:
      description: Bad request.
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message: 
                type: string
              data:
                type: object
          example:
            code: 400
            message: Bad Request
            data: 
    401UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message: 
                type: string
              data:
                type: object
          example:
            code: 401
            message: Access token is missing or invalid
            data:
    404NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message: 
                type: string
              data:
                type: object
          example:
            code: 404
            message: Not Found
            data:
    500InternalServerError:
      description: "Error from server"
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message: 
                type: string
              data:
                type: object
          example:
            code: 500
            message: There is some problem on server
            data: 

  